import csv
import io
from backend.schemas.protection_schema import ProtectionSettingsSchema, CurveType

class GEMultilinDriver:
    """Generador de archivos de configuración (.csv) para GE EnerVista Setup Software."""
    
    @staticmethod
    def map_curve_to_enervista(curve: CurveType) -> str:
        if not curve:
            return "IEEE Very Inverse"
        mapping = {
            CurveType.IEEE_MODERATELY_INVERSE: "IEEE Moderately Inverse",
            CurveType.IEEE_VERY_INVERSE: "IEEE Very Inverse",
            CurveType.IEEE_EXTREMELY_INVERSE: "IEEE Extremely Inverse",
            CurveType.ANSI_MODERATELY_INVERSE: "IEEE Moderately Inverse",
            CurveType.ANSI_VERY_INVERSE: "IEEE Very Inverse",
            CurveType.ANSI_EXTREMELY_INVERSE: "IEEE Extremely Inverse",
            CurveType.IEC_STANDARD_INVERSE: "IEC Curve A (BS142)",
            CurveType.IEC_VERY_INVERSE: "IEC Curve B (BS142)",
            CurveType.IEC_EXTREMELY_INVERSE: "IEC Curve C (BS142)",
            CurveType.DEFINITE_TIME: "Definite Time"
        }
        return mapping.get(curve, "IEEE Very Inverse")

    def generate_enervista_csv(self, settings: ProtectionSettingsSchema) -> str:
        output = io.StringIO()
        writer = csv.writer(output, delimiter=',')
        
        # Encabezado estándar de importación EnerVista
        writer.writerow(["# GE Multilin EnerVista Import Settings File"])
        writer.writerow(["# Generated by Vela Protection Copilot / E-Voltage Audit System"])
        writer.writerow(["# Substation", settings.substation_name])
        writer.writerow(["# Feeder", settings.feeder_id])
        writer.writerow(["# Target Relay", f"{settings.relay_brand} {settings.relay_model}"])
        writer.writerow([])
        writer.writerow(["Setting Name", "Value", "Units", "Description"])
        
        # Ajustes de TC / TT
        writer.writerow(["SYSTEM_CT_PRIMARY", settings.ct_ratio.primary_a, "A", "Phase CT Primary Rating"])
        writer.writerow(["SYSTEM_CT_SECONDARY", settings.ct_ratio.secondary_a, "A", "Phase CT Secondary Rating"])
        
        if settings.vt_ratio:
            writer.writerow(["SYSTEM_VT_PRIMARY", settings.vt_ratio.primary_v, "V", "Phase VT Primary Rating"])
            writer.writerow(["SYSTEM_VT_SECONDARY", settings.vt_ratio.secondary_v, "V", "Phase VT Secondary Rating"])
            
        # ANSI 51 (Sobrecorriente de Fase)
        if settings.ansi_51_phase and settings.ansi_51_phase.enabled:
            phase = settings.ansi_51_phase
            writer.writerow(["POC1_FUNCTION", "Enabled", "", "Phase Overcurrent 1 Status"])
            pickup_str = f"{phase.pickup_secondary_a:.3f}" if phase.pickup_secondary_a is not None else "1.000"
            tdm_str = f"{phase.time_dial:.2f}" if phase.time_dial is not None else "0.50"
            delay_str = f"{phase.delay_time_s:.2f}" if phase.delay_time_s is not None else "0.00"
            
            writer.writerow(["POC1_PICKUP", pickup_str, "pu", "Phase Overcurrent 1 Pickup Secondary"])
            writer.writerow(["POC1_CURVE", self.map_curve_to_enervista(phase.curve), "", "Phase Overcurrent 1 Curve Shape"])
            writer.writerow(["POC1_TDM", tdm_str, "", "Phase Overcurrent 1 Time Dial Multiplier"])
            writer.writerow(["POC1_DELAY", delay_str, "s", "Phase Overcurrent 1 Definite Time Delay"])

        # ANSI 51N (Sobrecorriente de Tierra)
        if settings.ansi_51n_ground and settings.ansi_51n_ground.enabled:
            ground = settings.ansi_51n_ground
            writer.writerow(["GOC1_FUNCTION", "Enabled", "", "Ground Overcurrent 1 Status"])
            pickup_str = f"{ground.pickup_secondary_a:.4f}" if ground.pickup_secondary_a is not None else "0.1000"
            tdm_str = f"{ground.time_dial:.2f}" if ground.time_dial is not None else "0.50"
            delay_str = f"{ground.delay_time_s:.2f}" if ground.delay_time_s is not None else "0.00"
            
            writer.writerow(["GOC1_PICKUP", pickup_str, "pu", "Ground Overcurrent 1 Pickup Secondary"])
            writer.writerow(["GOC1_CURVE", self.map_curve_to_enervista(ground.curve), "", "Ground Overcurrent 1 Curve Shape"])
            writer.writerow(["GOC1_TDM", tdm_str, "", "Ground Overcurrent 1 Time Dial Multiplier"])
            writer.writerow(["GOC1_DELAY", delay_str, "s", "Ground Overcurrent 1 Definite Time Delay"])

        return output.getvalue()
